version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: new_elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: new_kibana
    ports:
      - 5601:5601
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: new_logstash
    volumes:
      - ./logstash/config/:/usr/share/logstash/pipeline/
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
    networks:
      - elk_network

  nginx:
    image: nginx:latest
    container_name: new_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - elk_network

  haproxy:
    image: haproxy:latest
    container_name: new_haproxy
    ports:
      - 8080:8080
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - elk_network

  tomcat_a:
    image: tomcat:latest
    container_name: tomcat_a
    ports:
      - 8081:8080
    networks:
      - elk_network

  tomcat_b:
    image: tomcat:latest
    container_name: tomcat_b
    ports:
      - 8082:8080
    networks:
      - elk_network

  mysql:
    image: mysql:latest
    container_name: new_mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
    networks:
      - elk_network

  redis:
    image: redis:latest
    container_name: new_redis
    command: redis-server --port 6379
    networks:
      - elk_network

  rabbitmq:
    image: rabbitmq:latest
    container_name: new_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - elk_network

  nexus:
    image: sonatype/nexus3:latest
    container_name: new_nexus
    ports:
      - 8083:8081
    volumes:
      - ./nexus/data:/nexus-data
    networks:
      - elk_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:C:/Users/exo_x/OneDrive/Masaüstü/Dosyalar/Docker_case/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - elk_network
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.x
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: metricbeat -e
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  elk_network:
    driver: bridge
